name: ci
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
jobs:
  golangici-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "1.14"
      - name: install golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.27.0
      - run: |
          go mod download
          golangci-lint run -v
  go-test:
    strategy:
      matrix:
        os: [ubuntu-latest]
        go: ["1.14"]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - run: |
          docker-compose up -d redis
      - run: |
          go test -cover -coverprofile coverage.txt -race -v ./...
      - uses: codecov/codecov-action@v1
